### ISSUE TITLE
BUG with same action name

### ISSUE THREAD

**Issue by Tusko** [shooterRao/vue-plugin-event-bus#1]
I have an error with redefining function to the listener with the same name, for ex.:

```
// Subheader.vue
this.$eventBus.emit('reload');

// CompanyModal.vue
this.$eventBus.emit('reload');

// ProfileModal.vue
this.$eventBus.emit('reload');

// Profiles.vue (profile modal inside)
this.$eventBus.on('reload', () => this.fetchProfiles(), this);

// Companies.vue (profile modal inside)
this.$eventBus.on('reload', () => this.fetchCompanies(), this);
```

In this way, I can't reassign a new function on every new page (vue router)

**Comment by shooterRao** [comment]
@Tusko Hi~ Thanks a lot for asking this question~

But maybe it's not a bug?

The $eventBus event is collected with this(current vue instance). When the instance is destroyed, the event will also be auto cleared.

When has the same name，also can push array：

```js
_handleEventMap(event, compInstance) {
        this.eventCompMap[event]
          ? this.eventCompMap[event].push(compInstance)
          : (this.eventCompMap[event] = [compInstance]);
      },
```

Or...Would you mind provide more detailed code examples？🤔

**Comment by Tusko** [comment]
@shooterRao 
Fixed!
Just added `this` as last argument into `$eventBus.on(`

Thanks!
